package eu.kanade.tachiyomi.extension.all.ehentai

/**
 * Comprehensive E-Hentai tag dictionary used to power tag autocomplete suggestions.
 *
 * Each entry is a fully-qualified E-Hentai search token in the form "namespace:tag"
 * (lowercase, spaces allowed in the tag part). These are exactly the strings that get
 * typed into E-Hentai's f_search box, e.g. "female:big breasts", "parody:naruto".
 *
 * Grouped by namespace below. The curated female/male/other lists are the well-known
 * popular sets; language is the full set of E-Hentai language tags; parody/character
 * are curated sets of the most commonly used franchises and characters; artist/group
 * are intentionally small (only clearly common ones); reclass/mixed are the small
 * standard sets.
 */
val EH_TAG_SUGGESTIONS: List<String> = listOf(
    // ---------------------------------------------------------------------
    // language:
    // ---------------------------------------------------------------------
    "language:japanese",
    "language:english",
    "language:chinese",
    "language:dutch",
    "language:french",
    "language:german",
    "language:hungarian",
    "language:italian",
    "language:korean",
    "language:polish",
    "language:portuguese",
    "language:russian",
    "language:spanish",
    "language:thai",
    "language:vietnamese",
    "language:n/a",
    "language:other",
    "language:rewrite",
    "language:translated",
    "language:speechless",
    "language:text cleaned",

    // ---------------------------------------------------------------------
    // female:
    // ---------------------------------------------------------------------
    "female:ahegao",
    "female:anal",
    "female:angel",
    "female:apron",
    "female:bandages",
    "female:bbw",
    "female:bdsm",
    "female:beauty mark",
    "female:big areolae",
    "female:big ass",
    "female:big breasts",
    "female:big clit",
    "female:big lips",
    "female:big nipples",
    "female:bikini",
    "female:blackmail",
    "female:bloomers",
    "female:blowjob",
    "female:bodysuit",
    "female:bondage",
    "female:breast expansion",
    "female:bukkake",
    "female:bunny girl",
    "female:business suit",
    "female:catgirl",
    "female:centaur",
    "female:cheating",
    "female:chinese dress",
    "female:christmas",
    "female:collar",
    "female:corset",
    "female:cosplaying",
    "female:cowgirl",
    "female:crossdressing",
    "female:cunnilingus",
    "female:dark skin",
    "female:daughter",
    "female:deepthroat",
    "female:defloration",
    "female:demon girl",
    "female:double penetration",
    "female:dougi",
    "female:dragon",
    "female:drunk",
    "female:elf",
    "female:exhibitionism",
    "female:farting",
    "female:females only",
    "female:femdom",
    "female:filming",
    "female:fingering",
    "female:fishnets",
    "female:footjob",
    "female:fox girl",
    "female:furry",
    "female:futanari",
    "female:garter belt",
    "female:ghost",
    "female:giantess",
    "female:glasses",
    "female:gloves",
    "female:goblin",
    "female:gothic lolita",
    "female:growth",
    "female:guro",
    "female:gyaru",
    "female:hair buns",
    "female:hairy",
    "female:hairy armpits",
    "female:handjob",
    "female:harem",
    "female:hidden sex",
    "female:horns",
    "female:huge breasts",
    "female:humiliation",
    "female:impregnation",
    "female:incest",
    "female:inverted nipples",
    "female:kemonomimi",
    "female:kimono",
    "female:kissing",
    "female:lactation",
    "female:latex",
    "female:leg lock",
    "female:leotard",
    "female:lingerie",
    "female:lizard girl",
    "female:maid",
    "female:masked face",
    "female:masturbation",
    "female:midget",
    "female:miko",
    "female:milf",
    "female:mind break",
    "female:mind control",
    "female:monster girl",
    "female:mother",
    "female:muscle",
    "female:nakadashi",
    "female:netorare",
    "female:nose hook",
    "female:nun",
    "female:nurse",
    "female:oil",
    "female:paizuri",
    "female:panda girl",
    "female:pantyhose",
    "female:piercing",
    "female:pixie cut",
    "female:policewoman",
    "female:ponytail",
    "female:pregnant",
    "female:rape",
    "female:rimjob",
    "female:robot",
    "female:scat",
    "female:schoolgirl uniform",
    "female:sex toys",
    "female:shemale",
    "female:sister",
    "female:small breasts",
    "female:smell",
    "female:sole dickgirl",
    "female:sole female",
    "female:squirting",
    "female:stockings",
    "female:sundress",
    "female:sweating",
    "female:swimsuit",
    "female:swinging",
    "female:tail",
    "female:tall girl",
    "female:teacher",
    "female:tentacles",
    "female:thigh high boots",
    "female:tomboy",
    "female:transformation",
    "female:twins",
    "female:twintails",
    "female:unusual pupils",
    "female:urination",
    "female:vore",
    "female:vtuber",
    "female:widow",
    "female:wings",
    "female:witch",
    "female:wolf girl",
    "female:x-ray",
    "female:yuri",
    "female:zombie",

    // ---------------------------------------------------------------------
    // male:
    // ---------------------------------------------------------------------
    "male:anal",
    "male:bbm",
    "male:big ass",
    "male:big penis",
    "male:bikini",
    "male:blood",
    "male:blowjob",
    "male:bondage",
    "male:catboy",
    "male:cheating",
    "male:chikan",
    "male:condom",
    "male:crab",
    "male:crossdressing",
    "male:dark skin",
    "male:deepthroat",
    "male:demon",
    "male:dickgirl on male",
    "male:dilf",
    "male:dog boy",
    "male:double anal",
    "male:double penetration",
    "male:dragon",
    "male:drunk",
    "male:exhibitionism",
    "male:facial hair",
    "male:feminization",
    "male:footjob",
    "male:fox boy",
    "male:furry",
    "male:glasses",
    "male:group",
    "male:guro",
    "male:hairy",
    "male:handjob",
    "male:hidden sex",
    "male:horns",
    "male:huge penis",
    "male:human on furry",
    "male:kimono",
    "male:lingerie",
    "male:lizard guy",
    "male:machine",
    "male:maid",
    "male:males only",
    "male:masturbation",
    "male:mmm threesome",
    "male:monster",
    "male:muscle",
    "male:nakadashi",
    "male:ninja",
    "male:octopus",
    "male:oni",
    "male:pillory",
    "male:policeman",
    "male:possession",
    "male:prostate massage",
    "male:public use",
    "male:schoolboy uniform",
    "male:schoolgirl uniform",
    "male:sex toys",
    "male:shotacon",
    "male:sleeping",
    "male:snuff",
    "male:sole male",
    "male:stockings",
    "male:sunglasses",
    "male:swimsuit",
    "male:tall man",
    "male:tentacles",
    "male:tomgirl",
    "male:unusual pupils",
    "male:virginity",
    "male:waiter",
    "male:x-ray",
    "male:yaoi",
    "male:zombie",

    // ---------------------------------------------------------------------
    // other:
    // ---------------------------------------------------------------------
    "other:3d",
    "other:already uploaded",
    "other:anaglyph",
    "other:animated",
    "other:anthology",
    "other:artbook",
    "other:caption",
    "other:comic",
    "other:compilation",
    "other:dakimakura",
    "other:female",
    "other:figure",
    "other:forbidden content",
    "other:full censorship",
    "other:full color",
    "other:game sprite",
    "other:group",
    "other:how to",
    "other:incest",
    "other:incomplete",
    "other:missing cover",
    "other:mosaic censorship",
    "other:multi-work series",
    "other:no penetration",
    "other:non-nude",
    "other:novel",
    "other:nudity only",
    "other:out of order",
    "other:poor grammar",
    "other:sample",
    "other:scanmark",
    "other:screenshots",
    "other:sketch lines",
    "other:story arc",
    "other:tankoubon",
    "other:themeless",
    "other:time stop",
    "other:twins",
    "other:uncensored",
    "other:variant set",
    "other:vertical",
    "other:watermarked",
    "other:webtoon",
    "other:western cg",
    "other:western imageset",
    "other:western non-h",

    // ---------------------------------------------------------------------
    // parody: (most popular franchises; "original" is the single most common)
    // ---------------------------------------------------------------------
    "parody:original",
    "parody:touhou project",
    "parody:fate grand order",
    "parody:fate stay night",
    "parody:fate kaleid liner prisma illya",
    "parody:kantai collection",
    "parody:azur lane",
    "parody:genshin impact",
    "parody:honkai star rail",
    "parody:honkai impact 3rd",
    "parody:the idolmaster",
    "parody:the idolmaster cinderella girls",
    "parody:the idolmaster shiny colors",
    "parody:the idolmaster million live",
    "parody:love live",
    "parody:love live sunshine",
    "parody:love live nijigasaki academy school idol club",
    "parody:granblue fantasy",
    "parody:princess connect",
    "parody:uma musume pretty derby",
    "parody:arknights",
    "parody:blue archive",
    "parody:nikke",
    "parody:girls frontline",
    "parody:goddess of victory nikke",
    "parody:neon genesis evangelion",
    "parody:naruto",
    "parody:one piece",
    "parody:pokemon",
    "parody:dragon ball",
    "parody:bleach",
    "parody:fairy tail",
    "parody:my hero academia",
    "parody:attack on titan",
    "parody:sword art online",
    "parody:re zero",
    "parody:konosuba",
    "parody:overlord",
    "parody:goblin slayer",
    "parody:spy x family",
    "parody:chainsaw man",
    "parody:jujutsu kaisen",
    "parody:kimetsu no yaiba",
    "parody:hunter x hunter",
    "parody:yu-gi-oh",
    "parody:digimon",
    "parody:inazuma eleven",
    "parody:sailor moon",
    "parody:cardcaptor sakura",
    "parody:precure",
    "parody:gintama",
    "parody:jojos bizarre adventure",
    "parody:one punch man",
    "parody:mob psycho 100",
    "parody:saint seiya",
    "parody:fist of the north star",
    "parody:berserk",
    "parody:gundam",
    "parody:code geass",
    "parody:to love-ru",
    "parody:highschool dxd",
    "parody:date a live",
    "parody:nisekoi",
    "parody:bakemonogatari",
    "parody:monogatari series",
    "parody:steins gate",
    "parody:no game no life",
    "parody:log horizon",
    "parody:accel world",
    "parody:darling in the franxx",
    "parody:kill la kill",
    "parody:gurren lagann",
    "parody:panty stocking with garterbelt",
    "parody:macross",
    "parody:macross frontier",
    "parody:k-on",
    "parody:lucky star",
    "parody:the melancholy of haruhi suzumiya",
    "parody:clannad",
    "parody:toaru majutsu no index",
    "parody:a certain scientific railgun",
    "parody:nichijou",
    "parody:new game",
    "parody:yuru camp",
    "parody:non non biyori",
    "parody:gochuumon wa usagi desu ka",
    "parody:bang dream",
    "parody:d4dj",
    "parody:project sekai",
    "parody:ensemble stars",
    "parody:a3",
    "parody:the quintessential quintuplets",
    "parody:kanojo okarishimasu",
    "parody:saekano",
    "parody:oregairu",
    "parody:toradora",
    "parody:senran kagura",
    "parody:queens blade",
    "parody:ikkitousen",
    "parody:girls und panzer",
    "parody:kemono friends",
    "parody:vocaloid",
    "parody:hololive",
    "parody:nijisanji",
    "parody:kaguya-sama love is war",
    "parody:the seven deadly sins",
    "parody:black lagoon",
    "parody:fire emblem",
    "parody:fire emblem three houses",
    "parody:fire emblem heroes",
    "parody:fire emblem awakening",
    "parody:xenoblade chronicles",
    "parody:splatoon",
    "parody:super mario brothers",
    "parody:the legend of zelda",
    "parody:metroid",
    "parody:kirby",
    "parody:sonic the hedgehog",
    "parody:mega man",
    "parody:animal crossing",
    "parody:monster hunter",
    "parody:final fantasy",
    "parody:final fantasy vii",
    "parody:final fantasy xiv",
    "parody:persona 5",
    "parody:persona 4",
    "parody:persona 3",
    "parody:tales of",
    "parody:nier automata",
    "parody:nier",
    "parody:street fighter",
    "parody:the king of fighters",
    "parody:dead or alive",
    "parody:darkstalkers",
    "parody:guilty gear",
    "parody:resident evil",
    "parody:metal gear solid",
    "parody:cyberpunk 2077",
    "parody:elden ring",
    "parody:dark souls",
    "parody:undertale",
    "parody:helltaker",
    "parody:five nights at freddys",
    "parody:danganronpa",
    "parody:doki doki literature club",
    "parody:league of legends",
    "parody:overwatch",
    "parody:world of warcraft",
    "parody:diablo",
    "parody:warhammer 40k",
    "parody:my little pony friendship is magic",
    "parody:avatar the last airbender",
    "parody:disney",
    "parody:frozen",
    "parody:rick and morty",
    "parody:gravity falls",
    "parody:star wars",
    "parody:marvel",
    "parody:dc comics",
    "parody:batman",
    "parody:spider-man",
    "parody:harry potter",
    "parody:teenage mutant ninja turtles",

    // ---------------------------------------------------------------------
    // character:
    // ---------------------------------------------------------------------
    // Touhou
    "character:reimu hakurei",
    "character:marisa kirisame",
    "character:remilia scarlet",
    "character:flandre scarlet",
    "character:sakuya izayoi",
    "character:patchouli knowledge",
    "character:cirno",
    "character:sanae kochiya",
    "character:yukari yakumo",
    "character:komeiji koishi",
    "character:komeiji satori",
    "character:fujiwara no mokou",
    "character:houraisan kaguya",
    "character:reisen udongein inaba",
    // Fate
    "character:artoria pendragon",
    "character:saber",
    "character:rin tohsaka",
    "character:sakura matou",
    "character:illyasviel von einzbern",
    "character:mash kyrielight",
    "character:jeanne darc",
    "character:scathach",
    "character:tamamo no mae",
    "character:nero claudius",
    // Evangelion
    "character:asuka langley soryu",
    "character:rei ayanami",
    "character:mari makinami illustrious",
    "character:misato katsuragi",
    // KanColle / Azur Lane
    "character:kongou",
    "character:shimakaze",
    "character:kaga",
    "character:akagi",
    "character:atago",
    "character:takao",
    "character:tenryuu",
    "character:enterprise",
    "character:belfast",
    // Genshin / Hoyoverse
    "character:ganyu",
    "character:raiden shogun",
    "character:hu tao",
    "character:yae miko",
    "character:kamisato ayaka",
    "character:lumine",
    "character:paimon",
    "character:mona megistus",
    "character:keqing",
    "character:yelan",
    "character:nahida",
    "character:furina",
    // One Piece
    "character:nico robin",
    "character:nami",
    "character:boa hancock",
    // Naruto
    "character:naruto uzumaki",
    "character:sakura haruno",
    "character:hinata hyuga",
    "character:tsunade",
    "character:sasuke uchiha",
    "character:ino yamanaka",
    "character:temari",
    // My Hero Academia
    "character:ochaco uraraka",
    "character:momo yaoyorozu",
    "character:tsuyu asui",
    "character:mina ashido",
    "character:mei hatsume",
    "character:katsuki bakugou",
    "character:izuku midoriya",
    // Attack on Titan
    "character:mikasa ackerman",
    "character:historia reiss",
    "character:annie leonhart",
    "character:sasha braus",
    // Sword Art Online
    "character:asuna",
    "character:kirito",
    "character:sinon",
    "character:silica",
    "character:leafa",
    // Re:Zero / KonoSuba
    "character:rem",
    "character:ram",
    "character:emilia",
    "character:megumin",
    "character:aqua",
    "character:darkness",
    // Chainsaw Man / JJK / Demon Slayer
    "character:power",
    "character:makima",
    "character:nezuko kamado",
    "character:shinobu kocho",
    "character:mitsuri kanroji",
    "character:gojo satoru",
    "character:nobara kugisaki",
    // Spy x Family
    "character:yor forger",
    "character:anya forger",
    // Kaguya-sama / Darling / Kill la Kill
    "character:chika fujiwara",
    "character:kaguya shinomiya",
    "character:zero two",
    "character:ryuko matoi",
    "character:mako mankanshoku",
    // NieR / FF
    "character:2b",
    "character:a2",
    "character:tifa lockhart",
    "character:aerith gainsborough",
    "character:yuffie kisaragi",
    "character:cloud strife",
    // Resident Evil / Tomb Raider
    "character:jill valentine",
    "character:ada wong",
    "character:claire redfield",
    "character:lara croft",
    // Fighting games
    "character:chun-li",
    "character:cammy white",
    "character:mai shiranui",
    "character:morrigan aensland",
    // Overwatch / League
    "character:d.va",
    "character:mercy",
    "character:widowmaker",
    "character:tracer",
    "character:ahri",
    // Nintendo
    "character:samus aran",
    "character:princess peach",
    "character:princess zelda",
    "character:bowsette",
    // Pokemon
    "character:misty",
    "character:dawn",
    "character:may",
    "character:serena",
    "character:lillie",
    "character:gardevoir",
    "character:lucario",
    // Dragon Ball
    "character:bulma",
    "character:android 18",
    "character:chi-chi",
    "character:videl",
    // Vocaloid
    "character:hatsune miku",

    // ---------------------------------------------------------------------
    // artist: (intentionally small — only clearly common ones)
    // ---------------------------------------------------------------------
    "artist:oda non",
    "artist:homunculus",
    "artist:takeda hiromitsu",
    "artist:distance",
    "artist:shindol",
    "artist:okayado",
    "artist:itou life",
    "artist:yamatogawa",
    "artist:karory",
    "artist:fuetakishi",
    "artist:bosshi",
    "artist:inoue kiyoshirou",
    "artist:mizuryu kei",
    "artist:fan no hitori",
    "artist:saburo",

    // ---------------------------------------------------------------------
    // group: (intentionally small — only clearly common ones)
    // ---------------------------------------------------------------------
    "group:crimson comics",
    "group:circle eden",
    "group:gold rush",
    "group:alice no takarabako",
    "group:u.r.c",

    // ---------------------------------------------------------------------
    // mixed: (small standard set)
    // ---------------------------------------------------------------------
    "mixed:nakadashi",
    "mixed:group",
    "mixed:netorare",
    "mixed:swinging",
    "mixed:incest",
    "mixed:harem",
    "mixed:double penetration",
    "mixed:threesome",

    // ---------------------------------------------------------------------
    // reclass: (standard reclassification targets)
    // ---------------------------------------------------------------------
    "reclass:doujinshi",
    "reclass:manga",
    "reclass:artist cg",
    "reclass:game cg",
    "reclass:western",
    "reclass:non-h",
    "reclass:image set",
    "reclass:cosplay",
    "reclass:asian porn",
    "reclass:misc",
)
