package eu.kanade.tachiyomi.extension.id.manhwalandmom

import eu.kanade.tachiyomi.source.model.Filter

open class SelectFilter(displayName: String, private val pairs: Array<Pair<String, String>>) : Filter.Select<String>(displayName, pairs.map { it.first }.toTypedArray()) {
    fun toUriPart() = pairs[state].second
}

class SortFilter :
    SelectFilter(
        "Urutkan",
        arrayOf(
            Pair("Relevansi", ""),
            Pair("Populer", "popular"),
            Pair("Terbaru", "newest"),
            Pair("Judul A-Z", "title"),
        ),
    )

class StatusFilter :
    SelectFilter(
        "Status",
        arrayOf(
            Pair("Semua", ""),
            Pair("Ongoing", "Ongoing"),
            Pair("Completed", "Completed"),
        ),
    )

class TypeFilter :
    SelectFilter(
        "Tipe",
        arrayOf(
            Pair("Semua", ""),
            Pair("Manga", "Manga"),
            Pair("Manhua", "Manhua"),
            Pair("Manhwa", "Manhwa"),
        ),
    )

// Only used when the text query is blank: routes to the dedicated
// /genres/<slug> browse page instead of /search (which requires a query).
class GenreFilter : SelectFilter("Genre (hanya jika teks pencarian kosong)", GENRES)

val GENRES = arrayOf(
    Pair("Semua", ""),
    Pair("Action", "action"),
    Pair("Adilt", "adilt"),
    Pair("Adult", "adult"),
    Pair("Adventure", "adventure"),
    Pair("Age Progression", "age-progression"),
    Pair("Age Regression", "age-regression"),
    Pair("Ahegao", "ahegao"),
    Pair("Akadashi", "akadashi"),
    Pair("All The Way Through", "all-the-way-through"),
    Pair("Amputee", "amputee"),
    Pair("Anal", "anal"),
    Pair("Anorexia", "anorexia"),
    Pair("Apron", "apron"),
    Pair("Artist CG", "artist-cg"),
    Pair("Aunt", "aunt"),
    Pair("Bald", "bald"),
    Pair("Bbew", "bbew"),
    Pair("Bbm", "bbm"),
    Pair("Bbw", "bbw"),
    Pair("BDSM", "bdsm"),
    Pair("Beauty Mark", "beauty-mark"),
    Pair("Bestiality", "bestiality"),
    Pair("Big Areolae", "big-areolae"),
    Pair("Big Ass", "big-ass"),
    Pair("Big Breas", "big-breas"),
    Pair("Big Breast", "big-breast"),
    Pair("Big Breast Sole Female", "big-breast-sole-female"),
    Pair("Big Breasts", "big-breasts"),
    Pair("Big Dick", "big-dick"),
    Pair("Big Nipples", "big-nipples"),
    Pair("Big Penis", "big-penis"),
    Pair("Bike Shorts", "bike-shorts"),
    Pair("Bikini", "bikini"),
    Pair("Birth", "birth"),
    Pair("Bisexual", "bisexual"),
    Pair("Biting", "biting"),
    Pair("Black Mail", "black-mail"),
    Pair("Blackmail", "blackmail"),
    Pair("Blindfold", "blindfold"),
    Pair("Bloomers", "bloomers"),
    Pair("Blowjob", "blowjob"),
    Pair("Blowjob Face", "blowjob-face"),
    Pair("Body Swap", "body-swap"),
    Pair("Bodysuit", "bodysuit"),
    Pair("Bondage", "bondage"),
    Pair("Booty", "booty"),
    Pair("Bowjob", "bowjob"),
    Pair("Breast Feeding", "breast-feeding"),
    Pair("Bride", "bride"),
    Pair("Bukkake", "bukkake"),
    Pair("Bunny Girl", "bunny-girl"),
    Pair("Business Suit", "business-suit"),
    Pair("Busty", "busty"),
    Pair("Cat Girl", "cat-girl"),
    Pair("Catgirl", "catgirl"),
    Pair("Censored", "censored"),
    Pair("Cheating", "cheating"),
    Pair("Chool Uniform", "chool-uniform"),
    Pair("Chubby", "chubby"),
    Pair("Collar", "collar"),
    Pair("College", "college"),
    Pair("Colored", "colored"),
    Pair("Comedi", "comedi"),
    Pair("Comedy", "comedy"),
    Pair("Condom", "condom"),
    Pair("Cooking", "cooking"),
    Pair("Cosplay", "cosplay"),
    Pair("Cousin", "cousin"),
    Pair("Cow Girl", "cow-girl"),
    Pair("Cowgirl", "cowgirl"),
    Pair("Creampie", "creampie"),
    Pair("Crossdressing", "crossdressing"),
    Pair("Cunnilingus", "cunnilingus"),
    Pair("Curly Hair", "curly-hair"),
    Pair("Dark Skin", "dark-skin"),
    Pair("Darkskin", "darkskin"),
    Pair("Daughter", "daughter"),
    Pair("Deepthroat", "deepthroat"),
    Pair("Defloration", "defloration"),
    Pair("Demon Girl", "demon-girl"),
    Pair("Demons", "demons"),
    Pair("Dick", "dick"),
    Pair("Dick Growth", "dick-growth"),
    Pair("Digital", "digital"),
    Pair("DILF", "dilf"),
    Pair("Double Penetration", "double-penetration"),
    Pair("Doujin", "doujin"),
    Pair("Drama", "drama"),
    Pair("Drugs", "drugs"),
    Pair("Drunk", "drunk"),
    Pair("Ecchi", "ecchi"),
    Pair("Elf", "elf"),
    Pair("Emotionless Sex", "emotionless-sex"),
    Pair("Exhibitionism", "exhibitionism"),
    Pair("Eyebrows", "eyebrows"),
    Pair("Eyepatch", "eyepatch"),
    Pair("Facial", "facial"),
    Pair("Family", "family"),
    Pair("Fangs", "fangs"),
    Pair("Fantasy", "fantasy"),
    Pair("Female", "female"),
    Pair("Female Only", "female-only"),
    Pair("Females Only", "females-only"),
    Pair("Femdom", "femdom"),
    Pair("Fffm Foursome", "fffm-foursome"),
    Pair("Ffm Threesome", "ffm-threesome"),
    Pair("Filming", "filming"),
    Pair("Fingering", "fingering"),
    Pair("Footjob", "footjob"),
    Pair("Force", "force"),
    Pair("Forced", "forced"),
    Pair("Foursome", "foursome"),
    Pair("Fuck Piercing", "fuck-piercing"),
    Pair("Full Color", "full-color"),
    Pair("Furry", "furry"),
    Pair("Futanari", "futanari"),
    Pair("Game", "game"),
    Pair("Gangbang", "gangbang"),
    Pair("Garter Belt", "garter-belt"),
    Pair("Gender Bender", "gender-bender"),
    Pair("Genres", "genres"),
    Pair("Ghost", "ghost"),
    Pair("Ghotic Lolita", "ghotic-lolita"),
    Pair("Glasses", "glasses"),
    Pair("Gloves", "gloves"),
    Pair("Gokkun", "gokkun"),
    Pair("Gore", "gore"),
    Pair("Group", "group"),
    Pair("Growth", "growth"),
    Pair("Guro", "guro"),
    Pair("Gyaru", "gyaru"),
    Pair("Hairy", "hairy"),
    Pair("Handjob", "handjob"),
    Pair("Harem", "harem"),
    Pair("Heart Pupils", "heart-pupils"),
    Pair("Hentai", "hentai"),
    Pair("Hidden Sex", "hidden-sex"),
    Pair("High School", "high-school"),
    Pair("Hipnotis", "hipnotis"),
    Pair("Historical", "historical"),
    Pair("Horn", "horn"),
    Pair("Horns", "horns"),
    Pair("Horror", "horror"),
    Pair("Hotpants", "hotpants"),
    Pair("House Wife", "house-wife"),
    Pair("HouseWife", "housewife"),
    Pair("Huge", "huge"),
    Pair("Huge Boobs", "huge-boobs"),
    Pair("Huge Breast", "huge-breast"),
    Pair("Huge Breasts", "huge-breasts"),
    Pair("Huge Penis", "huge-penis"),
    Pair("Humiliation", "humiliation"),
    Pair("Ig Breast", "ig-breast"),
    Pair("Ikini", "ikini"),
    Pair("Impregnant", "impregnant"),
    Pair("Impregnate", "impregnate"),
    Pair("Impregnation", "impregnation"),
    Pair("Incest", "incest"),
    Pair("Inflation", "inflation"),
    Pair("Insect", "insect"),
    Pair("Inseki", "inseki"),
    Pair("Inverted Nipples", "inverted-nipples"),
    Pair("Invisible", "invisible"),
    Pair("Isekai", "isekai"),
    Pair("Josei", "josei"),
    Pair("Katsuragi Keima", "katsuragi-keima"),
    Pair("Kemomimi", "kemomimi"),
    Pair("Kemonomimi", "kemonomimi"),
    Pair("Kimono", "kimono"),
    Pair("Kissing", "kissing"),
    Pair("Kogal", "kogal"),
    Pair("Kosaka Chihiro", "kosaka-chihiro"),
    Pair("Kuudere", "kuudere"),
    Pair("Lactation", "lactation"),
    Pair("Leotard", "leotard"),
    Pair("Lingerie", "lingerie"),
    Pair("Loli", "loli"),
    Pair("Lolicon", "lolicon"),
    Pair("Lolipai", "lolipai"),
    Pair("Love Hotel", "love-hotel"),
    Pair("Magic", "magic"),
    Pair("Maid", "maid"),
    Pair("Males Only", "males-only"),
    Pair("Mall Breast", "mall-breast"),
    Pair("Manga", "manga"),
    Pair("Manhua", "manhua"),
    Pair("Manhwa", "manhwa"),
    Pair("Mantap", "mantap"),
    Pair("Martial Arts", "martial-arts"),
    Pair("Massage", "massage"),
    Pair("Masturbation", "masturbation"),
    Pair("Mating Press", "mating-press"),
    Pair("Mature", "mature"),
    Pair("Mecha", "mecha"),
    Pair("Miko", "miko"),
    Pair("Milf", "milf"),
    Pair("Milftoon", "milftoon"),
    Pair("Military", "military"),
    Pair("Mind Break", "mind-break"),
    Pair("Mind Control", "mind-control"),
    Pair("Minigirl", "minigirl"),
    Pair("Monster", "monster"),
    Pair("Monster Girl", "monster-girl"),
    Pair("MonsterRape", "monsterrape"),
    Pair("Monsters", "monsters"),
    Pair("Mosaic Censorship", "mosaic-censorship"),
    Pair("Mother", "mother"),
    Pair("Motion", "motion"),
    Pair("Multi-Work Series", "multi-work-series"),
    Pair("Muscle", "muscle"),
    Pair("Muscles", "muscles"),
    Pair("Mystery", "mystery"),
    Pair("Nakadashi", "nakadashi"),
    Pair("Nal", "nal"),
    Pair("Ncest", "ncest"),
    Pair("Netorare", "netorare"),
    Pair("Netorase", "netorase"),
    Pair("Netori", "netori"),
    Pair("Niece", "niece"),
    Pair("Nipple", "nipple"),
    Pair("Nipple Fuck", "nipple-fuck"),
    Pair("Nipples", "nipples"),
    Pair("No Penetration", "no-penetration"),
    Pair("Ntr", "ntr"),
    Pair("Nu", "nu"),
    Pair("Nurse", "nurse"),
    Pair("Office Lady", "office-lady"),
    Pair("Office Workers", "office-workers"),
    Pair("Ojousama", "ojousama"),
    Pair("Old Man", "old-man"),
    Pair("Old Woman", "old-woman"),
    Pair("Original", "original"),
    Pair("Osananajimi", "osananajimi"),
    Pair("Outdoors", "outdoors"),
    Pair("Oyakodon", "oyakodon"),
    Pair("Paizuri", "paizuri"),
    Pair("Pantyhose", "pantyhose"),
    Pair("Parody", "parody"),
    Pair("Piercing", "piercing"),
    Pair("Ponytail", "ponytail"),
    Pair("Possession", "possession"),
    Pair("Pregnant", "pregnant"),
    Pair("Project", "project"),
    Pair("Prostitution", "prostitution"),
    Pair("Psychological", "psychological"),
    Pair("Pubic Hair", "pubic-hair"),
    Pair("Pupils", "pupils"),
    Pair("Rape", "rape"),
    Pair("Reincarnation", "reincarnation"),
    Pair("Rimjob", "rimjob"),
    Pair("Robot", "robot"),
    Pair("Romance", "romance"),
    Pair("Romance. Drama", "romance-drama"),
    Pair("Rough Translation", "rough-translation"),
    Pair("Scat", "scat"),
    Pair("School", "school"),
    Pair("School Girl", "school-girl"),
    Pair("School Girl Uniform", "school-girl-uniform"),
    Pair("School Life", "school-life"),
    Pair("School Uniform", "school-uniform"),
    Pair("Schoolgirl Outfit", "schoolgirl-outfit"),
    Pair("Sci-Fi", "sci-fi"),
    Pair("Seinen", "seinen"),
    Pair("Senior Girl", "senior-girl"),
    Pair("Sex Toys", "sex-toys"),
    Pair("Shemale", "shemale"),
    Pair("Shibari", "shibari"),
    Pair("Short Hair", "short-hair"),
    Pair("Shota", "shota"),
    Pair("Shotacon", "shotacon"),
    Pair("Shoujo", "shoujo"),
    Pair("Shoujo Ai", "shoujo-ai"),
    Pair("Shounen", "shounen"),
    Pair("Sister", "sister"),
    Pair("Slave", "slave"),
    Pair("Sleeping", "sleeping"),
    Pair("Slice of Life", "slice-of-life"),
    Pair("Slime", "slime"),
    Pair("Small Breast", "small-breast"),
    Pair("Small Breasts", "small-breasts"),
    Pair("Small Penis", "small-penis"),
    Pair("Smell", "smell"),
    Pair("Smut", "smut"),
    Pair("Snuff", "snuff"),
    Pair("Sole Female", "sole-female"),
    Pair("Sole Male", "sole-male"),
    Pair("Sports", "sports"),
    Pair("Sportswear", "sportswear"),
    Pair("Squirting", "squirting"),
    Pair("Stocking", "stocking"),
    Pair("Stockings", "stockings"),
    Pair("Story Arc", "story-arc"),
    Pair("Sumata", "sumata"),
    Pair("Supernatural", "supernatural"),
    Pair("Sweating", "sweating"),
    Pair("Swimsuit", "swimsuit"),
    Pair("Swinging", "swinging"),
    Pair("Tail", "tail"),
    Pair("Tall Girl", "tall-girl"),
    Pair("Tankoubon", "tankoubon"),
    Pair("Tanlines", "tanlines"),
    Pair("Teacher", "teacher"),
    Pair("Tentacles", "tentacles"),
    Pair("Threesome", "threesome"),
    Pair("Thriller", "thriller"),
    Pair("Tomboy", "tomboy"),
    Pair("Tomgirl", "tomgirl"),
    Pair("Torture", "torture"),
    Pair("Toys", "toys"),
    Pair("Tragedy", "tragedy"),
    Pair("Tsundere", "tsundere"),
    Pair("Twins", "twins"),
    Pair("Twintails", "twintails"),
    Pair("Ugly Bastard", "ugly-bastard"),
    Pair("Uncensored", "uncensored"),
    Pair("Uniform", "uniform"),
    Pair("Unusual Pupils", "unusual-pupils"),
    Pair("Vampire", "vampire"),
    Pair("Vanilla", "vanilla"),
    Pair("Video Games", "video-games"),
    Pair("Villainess", "villainess"),
    Pair("Virgin", "virgin"),
    Pair("Virginity", "virginity"),
    Pair("Voyeurism", "voyeurism"),
    Pair("Webtoon", "webtoon"),
    Pair("Webtoons", "webtoons"),
    Pair("Widow", "widow"),
    Pair("Wings", "wings"),
    Pair("X-Ra", "x-ra"),
    Pair("X-Ray", "x-ray"),
    Pair("Yandere", "yandere"),
    Pair("Yaoi", "yaoi"),
    Pair("Yuri", "yuri"),
)
